#!/bin/sh

system_type=$(uname -s)
if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # Install Homebrew bundle
  brewfile="$HOME/.config/homebrew/Brewfile"
  if [ -f $brewfile ]; then
    echo "Updating homebrew bundle"
    brew bundle --file=$brewfile
  fi

  # Set iTerm2 to use custom prefs directory
  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi
fi
